Change L2: Parenting MatrixH with a MatrixBase class in an attempt to unify all types and dim teplates of MatrixH. MatrixBase has mDims, dtype storing the dimension and type ehich are the templated parameters of its child MatrixH. This will allow us to create a proper tape and autograd system in which the parent of a mat can be mats with different dims for eg in brodcasted Add or different type for eg in Type conversion by putting matrixH of different type and dims in a std::vector<MatrixBase> parentNodes. and using the member vars of MatrixBase we will cast it to the correct templated MatrixH or atleast thats what i hope to achieve.
DeletionError: Removing the GPU Manager Code from MatrixH file as it was moved to its own module